# General Configuration
version: 1.0.1.{build}
skip_branch_with_pr: true

# Environment Configuration
image: Visual Studio 2017
cache:
  - '%LocalAppData%\NuGet\v3-cache'

install:
  #init and update submodules
  - git submodule update --recursive --init

 # version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'


# Build Configuration
platform: Any CPU
configuration: Release


before_build:
  - nuget restore

build:
  publish_nuget: true
  include_nuget_references: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  project: SpeckleStructural.sln
  verbosity: minimal

after_build:
# remove garbage
#  - ps: |
#      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleStructural\bin\Release\x86" -Recurse -ErrorAction Ignore
#      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleStructural\bin\Release\x64" -Recurse -ErrorAction Ignore
#      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleStructural\bin\Release\*.pdb" -Recurse -ErrorAction Ignore
#      Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleStructural\bin\Release\SpeckleStructural.dll.config" -Recurse -ErrorAction Ignore

# zip everything into a zip file containing package folder structure
  - 7z a SpeckleStructural.zip "%APPVEYOR_BUILD_FOLDER%\SpeckleStructural\bin\Release\*"

artifacts:
  path: SpeckleStructural.zip
  name: Release

#deploy to nuget
deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: n4EiHDLVSLjOzqT7OOOg3US3PWs6fNsOaGpyT/EFBKrTKl/1wMmmKt73MNuTngD+
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: nuget